# Generated by Django 4.0.2 on 2022-02-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0002_alter_song_album_alter_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_position', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='musiclib.PlaylistsSongs', to='musiclib.Song'),
        ),
        migrations.AddField(
            model_name='playlistssongs',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiclib.playlist'),
        ),
        migrations.AddField(
            model_name='playlistssongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiclib.song'),
        ),
    ]
