# Generated by Django 4.0.2 on 2022-02-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0003_playlistssongs_remove_song_playlist_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musiclib.artist'),
        ),
    ]
