# Generated by Django 4.0.2 on 2022-03-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0005_remove_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='some str', upload_to=''),
        ),
    ]
