# Generated by Django 4.0.2 on 2022-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0006_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to=''),
        ),
    ]
