# Generated by Django 4.0.2 on 2022-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0007_alter_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
