# Generated by Django 4.0.2 on 2022-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0008_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time_added',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
